[package]
name = "mcsim-itm"
description = "Rust wrapper for the NTIA Irregular Terrain Model (ITM)"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
libloading = "0.8"

[features]
default = []
